.TH AMOLDRECOVER 8
.SH NAME
amoldrecover \- amrecover variant compantible with old Amanda protocols
.SH "DESCRIPTION"
This program has the same syntax and functionality as amrecover, but uses
the older amidxtaped/amindexd protocol.  It is provided only for compatibility
with old Amanda releases.

This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.

.SH "SEE ALSO"
.PP
\fBamrecover\fR(8),

.SH AUTHOR
This manual page was written by Bdale Garbee <bdale@gag.com>,
for the Debian GNU/Linux system (but may be used by others).
